# Generated by Django 5.2.7 on 2025-11-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
    ]
