# Generated by Django 5.2.7 on 2025-11-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_department_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
    ]
