# Generated by Django 5.2.7 on 2025-11-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='patient_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='patient_phone',
        ),
    ]
