# Generated by Django 5.2.8 on 2025-11-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_doc_name_booking_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='dep_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
    ]
